// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abgvndknznaensqcahls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZ3ZuZGtuem5hZW5zcWNhaGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNTcyNTgsImV4cCI6MjA4OTYzMzI1OH0.JrOsCyLb57XQDrWEGod2D1FKlpHPSfNCDkL83eQ0hcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});